function [text filename filepath]=OnFileOpen()  
% This function is to open the sub file  

% Liuzheng 
% Copyright (c) 2012

% If you have some advises or problems , please mail to me
% Gmail:liuzheng712
% Thank you !

[filename,filepath]=uigetfile(...
    {'*.srt;*.ssa;*.sub;*ass;*.txt','Subtitle file (*.srt,*.ssa,*.sub,*.ass)';...
    '*.srt','Subripper (*.srt)';...
    '*.ssa','SubStation Alpha (*.ssa)';...
    '*.sub','SUB (*.sub)'; ...
    '*.sst','Sonic Scenarist (*.sst)';...
    '*.ass','Advanced SubStation Alpha (*.ass)';...
    '*.son','Spruce DVDMaestro (*.son)';...
    '*.smi','Sami (*.smi)';...
    '*.psb','Power Divx (*.psb)';...
    '*.pjs','Phoenix japanimation (*.pjs)';...
    '*.stl','Spruce subtittle flie (*.stl)';...
    '*.tts','Turbo tittle (*.tts)';...
    '*.vsf','Viplay (*.vsf)';...
    '*.zeg','Zero G (*.zeg)';...
    '*.*','All Files (*.*)'}); 
  
filep=strcat(filepath,filename);  
fid=fopen(filep,'r+','n','UTF-8');
text = fgets(fid);
tline = text;
text(1)=[];
while ischar(tline)
    tline = fgets(fid);
    text = strvcat(text,tline);
end

fclose(fid);
end
  